// Generated by LiveScript 1.5.0
(function(){
  var waves, eth, insight, toJS, ref$, pairsToObj, objToPairs, providers, action, getBalance, getTransactions, createTransaction, pushTx, out$ = typeof exports != 'undefined' && exports || this;
  waves = require('./providers/waves.ls');
  eth = require('./providers/eth.ls');
  insight = require('./providers/insight.ls');
  toJS = require('mobx').toJS;
  ref$ = require('prelude-ls'), pairsToObj = ref$.pairsToObj, objToPairs = ref$.objToPairs;
  providers = {
    eth: eth,
    waves: waves
  };
  action = function(func){
    return function(config, cb){
      var ref$, provider, ref1$;
      if (((ref$ = config.network) != null ? ref$.token : void 8) == null) {
        return cb("network.token is not defined");
      }
      provider = (ref1$ = providers[config.network.token]) != null ? ref1$ : insight;
      return func(provider, config, cb);
    };
  };
  out$.getBalance = getBalance = action(function(provider, config, cb){
    return provider.getBalance(config, cb);
  });
  out$.getTransactions = getTransactions = action(function(provider, config, cb){
    return provider.getTransactions(config, cb);
  });
  out$.createTransaction = createTransaction = action(function(provider, config, cb){
    return provider.createTransaction(config, cb);
  });
  out$.pushTx = pushTx = action(function(provider, config, cb){
    return provider.pushTx(config, cb);
  });
}).call(this);
