// Generated by LiveScript 1.6.0
(function(){
  var observer, observable, react, pages, whitebox, description, window, copyMessage, modalControl, getPrimaryInfo, getContainer;
  observer = require('mobx-react').observer;
  observable = require('mobx').observable;
  react = require('react');
  pages = require('./pages.ls');
  whitebox = require('whitebox');
  description = require('./description.ls');
  window = require('./browser/window.ls');
  copyMessage = require('./copy-message.ls');
  modalControl = require('./modal.ls').modalControl;
  getPrimaryInfo = require('./get-primary-info.ls');
  getContainer = whitebox.getContainer;
  module.exports = function(arg$){
    var store, reload, currentPage, style, children;
    store = arg$.store, reload = arg$.reload;
    if (store == null) {
      return null;
    }
    importAll$(window, {
      store: store
    });
    currentPage = pages[store.current.page];
    style = {
      backgroundColor: getPrimaryInfo(store).color
    };
    return react.createElement('div', {}, children = [
      description(store), react.createElement('div', {
        key: "content",
        style: style,
        className: 'app app872166188'
      }, children = [
        modalControl(store), copyMessage(store), currentPage({
          store: store
        })
      ])
    ]);
  };
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
