// Generated by LiveScript 1.5.0
(function(){
  var ref$, times, minus, plus, div, toJS, transaction, calcFee, changeAmount;
  ref$ = require('./math.ls'), times = ref$.times, minus = ref$.minus, plus = ref$.plus, div = ref$.div;
  ref$ = require('mobx'), toJS = ref$.toJS, transaction = ref$.transaction;
  calcFee = require('./api.ls').calcFee;
  changeAmount = function(store, amountSend){
    var send, ref$, wallet, token, resultAmountSend;
    send = store.current.send;
    ref$ = send.coin, wallet = ref$.wallet, token = ref$.token;
    resultAmountSend = amountSend != null ? amountSend : 0;
    return calcFee({
      token: token,
      network: send.network,
      amount: resultAmountSend
    }, function(err, calcedFee){
      var ref$, txFee, usdRate;
      if (err != null) {
        return send.error = "Calc Fee Error: " + ((ref$ = err.message) != null ? ref$ : err);
      }
      txFee = calcedFee != null
        ? calcedFee
        : send.network.txFee;
      usdRate = (ref$ = wallet != null ? wallet.usdRate : void 8) != null ? ref$ : 0;
      return transaction(function(){
        var sendUsd;
        send.amountSend = amountSend != null ? amountSend : "";
        send.value = times(resultAmountSend, Math.pow(10, send.network.decimals));
        sendUsd = times(resultAmountSend, usdRate);
        send.amountObtain = resultAmountSend;
        send.amountObtainUsd = times(send.amountObtain, usdRate);
        send.amountSendUsd = sendUsd;
        send.amountSendFee = txFee;
        send.amountCharged = plus(resultAmountSend, txFee);
        send.amountSendFeeUsd = times(txFee, usdRate);
        return send.error = parseFloat(minus(wallet.balance, resultAmountSend)) < 0 ? "Not Enough Funds" : "";
      });
    });
  };
  module.exports = changeAmount;
}).call(this);
