// Generated by LiveScript 1.6.0
(function(){
  var window;
  window = require('./browser/window.ls');
  module.exports = function(){
    return typeof window.close == 'function' ? window.close() : void 8;
  };
}).call(this);
