// Generated by LiveScript 1.5.0
(function(){
  module.exports = function(store){
    return function(event){
      store.current.copied = event;
      return setTimeout(function(){
        return store.current.copied = "";
      }, 3000);
    };
  };
}).call(this);
