// Generated by LiveScript 1.5.0
(function(){
  var react;
  react = require('react');
  module.exports = function(store){
    var copied, copiedClass, children;
    copied = store.current.copied;
    copiedClass = copied === '' ? '' : 'opened';
    return react.createElement('div', {
      className: copiedClass + " copied copied372389720"
    }, children = [react.createElement('div', {}, ' Copied'), react.createElement('div', {}, ' ' + copied)]);
  };
}).call(this);
