// Generated by LiveScript 1.6.0
(function(){
  var mainnet, testnet, txTypes, color, type, enabled, token, image, usdInfo, out$ = typeof exports != 'undefined' && exports || this;
  out$.mainnet = mainnet = {
    decimals: 8,
    txFee: '0.0001',
    txFeeOptions: {
      fast: '0.0001',
      cheap: '0.0000004',
      auto: '0.0001',
      instantPerInput: '0.001',
      privatePerInput: '0.05'
    },
    mask: 'X000000000000000000000000000000000',
    api: {
      provider: 'insight',
      url: 'https://insight.dash.org',
      mixingInfo: "url(https://mydashwallet.org/GeneratePrivateSendAddress?toAddress=:address)",
      decimal: 8
    },
    messagePrefix: '\x19DarkCoin Signed Message:\n',
    bip32: {
      'public': 0x02fe52f8,
      'private': 0x02fe52cc
    },
    pubKeyHash: 0x4c,
    scriptHash: 0x10,
    wif: 0xcc,
    dustThreshold: 5460
  };
  out$.testnet = testnet = {
    incorrect: true,
    decimals: 8,
    txFee: '0.0001',
    txFeeOptions: {
      auto: '0.0001',
      fast: '0.0001',
      cheap: '0.0000004'
    },
    mask: 'y000000000000000000000000000000000',
    topup: 'https://test.faucet.dashninja.pl/',
    api: {
      provider: 'insight',
      url: 'https://test.insight.dash.siampm.com',
      decimal: 8
    },
    messagePrefix: '\x19DarkCoin Signed Message:\n',
    bip32: {
      'public': 0x02fe52f8,
      'private': 0x02fe52cc
    },
    pubKeyHash: 0x8c,
    scriptHash: 0x13,
    wif: 0xef,
    dustThreshold: 5460
  };
  out$.txTypes = txTypes = ['regular', 'instant'];
  out$.color = color = '#649BF6';
  out$.type = type = 'coin';
  out$.enabled = enabled = true;
  out$.token = token = 'dash';
  out$.image = image = './res/dash-ethnamed.png';
  out$.usdInfo = usdInfo = "url(https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETH,LTC,DASH,XEM,USDT&tsyms=USD).DASH.USD";
}).call(this);
