// Generated by LiveScript 1.6.0
(function(){
  var getCoins, ref$, map, pairsToObj, saved, location, savedSeed, store;
  getCoins = require('./plugin-loader.ls').getCoins;
  ref$ = require('prelude-ls'), map = ref$.map, pairsToObj = ref$.pairsToObj;
  saved = require('./seed.ls').saved;
  location = require('./browser/location.ls');
  savedSeed = saved();
  store = {
    root: null,
    menu: {
      active: 's2'
    },
    ask: {
      text: '',
      enabled: false,
      callback: null,
      image: ""
    },
    current: {
      walletIndex: 0,
      demo: location.href.indexOf('ethnamed.io/wallet') > -1,
      network: 'mainnet',
      pin: "",
      lastTxUrl: "",
      tryEditSeed: false,
      pinTrial: 0,
      refreshing: false,
      copied: "",
      page: 'locked',
      sendToMask: "",
      status: 'main',
      nickname: "",
      nicknamefull: 'nickname@domain.com',
      message: "",
      customDomain: false,
      canBuy: false,
      checkingName: false,
      seed: "",
      savedSeed: savedSeed,
      balanceUsd: '...',
      filter: ['IN', 'OUT'],
      loading: false,
      send: {
        id: "",
        to: "",
        proposeEscrow: false,
        address: '',
        value: '0',
        amountSend: '0',
        amountCharged: '0',
        amountSendUsd: '0',
        amountSendFee: '0',
        amountSendFeeUsd: '0',
        amountObtain: '0',
        data: "",
        decodedData: "",
        showDataMode: 'encoded',
        error: ''
      }
    },
    rates: pairsToObj(
    map(function(it){
      return [
        it.token.toUpperCase(), {
          USD: 0
        }
      ];
    })(
    getCoins()))
  };
  module.exports = store;
}).call(this);
