// Generated by LiveScript 1.5.0
(function(){
  var newAccount, seed, networks, ref$, map, pairsToObj, savedSeed, seedStr;
  newAccount = require('./new-account.ls');
  seed = require('./seed.ls');
  networks = require('./networks.ls');
  ref$ = require('prelude-ls'), map = ref$.map, pairsToObj = ref$.pairsToObj;
  savedSeed = seed.get('seed').length > 0;
  seedStr = savedSeed ? seed.get('seed') : "Hello World";
  module.exports = {
    current: {
      refreshing: false,
      page: 'wallets',
      status: 'main',
      nickname: "",
      nicknamefull: 'nickname.domain.com',
      message: "",
      customDomain: false,
      canBuy: false,
      checkingName: false,
      seed: seedStr,
      savedSeed: savedSeed,
      account: newAccount(seedStr),
      balanceUsd: '...',
      filter: ['IN', 'OUT'],
      send: {
        id: "",
        to: "",
        address: '',
        value: '0',
        amountSend: '0',
        amountSendUsd: '0',
        amountSendFee: '0',
        amountSendFeeUsd: '0',
        amountObtain: '0',
        data: "",
        decodedData: "",
        showDataMode: 'encoded'
      }
    },
    rates: pairsToObj(
    map(function(it){
      return [
        it.toUpperCase(), {
          USD: 0
        }
      ];
    })(
    Object.keys(
    networks)))
  };
}).call(this);
