// Generated by LiveScript 1.6.0
(function(){
  var react;
  react = require('react');
  module.exports = function(store){
    var closeDemo, children, item;
    if (store.current.demo === false) {
      return null;
    }
    return null;
    closeDemo = function(){
      return store.current.demo = false;
    };
    return react.createElement('div', {
      key: "description",
      className: 'description description1821565793'
    }, children = [
      react.createElement('h1', {}, ' Ethnamed Smart-Wallet'), react.createElement('div', {
        className: 'line'
      }, children = [
        react.createElement('span', {}, ' This is a demo of the wallet connected to the '), react.createElement('a', {
          href: "https://github.com/ethnamed/protocol"
        }, ' Ethnamed protocol')
      ]), react.createElement('div', {
        className: 'line'
      }, ' Try to use this seed to see the testnet balance'), react.createElement('pre', {}, ' xmr bch btg ltc eth eos xem ada dash btc zec bcn'), react.createElement('pre', {}, ' PIN: 1234'), react.createElement('div', {
        className: 'line'
      }, children = [
        react.createElement('span', {}, ' You can try to register '), react.createElement('span', {
          className: 'mark'
        }, ' nickname@gmail.com'), react.createElement('span', {}, ' or'), react.createElement('span', {
          className: 'mark'
        }, ' nickname.ethnamed.io'), react.createElement('span', {}, '  You can try to send eth to another address. If address not found your still can send ETH to Ethnamed Smart-Contract. When user confirms his address he will get funds automatically.')
      ]), react.createElement('div', {
        className: 'line'
      }, children = [react.createElement('span', {}, ' It is still under construction - will be used as chrome plug-in (line Metamask) and mobile app. '), react.createElement('span', {}, ' Also it extends web3 protocol for btc, ltc, zec, dash networks available on the website')]), react.createElement('div', {
        className: 'line'
      }, children = react.createElement('span', {}, ' Example of the api (devtools):')), react.createElement('div', {
        className: 'line'
      }, children = react.createElement('pre', {}, children = [
        react.createElement('span', {
          className: 'part'
        }, ' web3t.use(`'), react.createElement('span', {
          className: 'part mark'
        }, ' mainnet'), react.createElement('span', {
          className: 'part'
        }, ' `); '), react.createElement('span', {}, ' or '), react.createElement('span', {
          className: 'part'
        }, ' web3t.use(`'), react.createElement('span', {
          className: 'part mark'
        }, ' testnet'), react.createElement('span', {
          className: 'part'
        }, ' `);')
      ])), (function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = ['eth', 'btc', 'xem']).length; i$ < len$; ++i$) {
          item = ref$[i$];
          results$.push(react.createElement('pre', {
            key: item + ""
          }, children = [
            react.createElement('span', {
              className: 'part'
            }, ' web3t.'), react.createElement('span', {
              className: 'part mark'
            }, ' ' + item), react.createElement('span', {
              className: 'part'
            }, ' .sendTransaction({ to, amount }, cb)')
          ]));
        }
        return results$;
      }()), react.createElement('div', {
        className: 'line'
      }, ' This is a new business oppurtunity for crypto entrepreneurs (no ICO, but tokenization of available functionality)'), react.createElement('div', {
        className: 'line'
      }, children = [
        react.createElement('span', {}, ' More information you can read in our '), react.createElement('a', {
          href: "https://docs.google.com/document/d/16W9E3lLrlkhbjklWLAEmPjF8Ovl8gBUmT8MsOZM0WjA/edit?usp=sharing"
        }, ' Whitepaper')
      ]), react.createElement('div', {
        className: 'line'
      }, children = [
        react.createElement('span', {}, ' All community member will get names '), react.createElement('span', {
          className: 'for-free'
        }, ' FOR FREE')
      ]), react.createElement('div', {
        className: 'line white'
      }, children = [
        react.createElement('a', {
          href: "https://t.me/ethnamed",
          className: 'big'
        }, ' Join our community'), react.createElement('a', {
          onClick: closeDemo,
          className: 'got-it'
        }, ' Close this')
      ]), react.createElement('div', {
        className: 'line who'
      }, children = [
        react.createElement('span', {}, ' Made with love. '), react.createElement('a', {
          href: "ethnamed.io"
        }, ' Ethnamed '), react.createElement('span', {}, ' team')
      ])
    ]);
  };
}).call(this);
