// Generated by LiveScript 1.6.0
(function(){
  var stringify, ref$, filter, map, foldl, each, plus, minus, times, div, get, Web3, Tx, BN, jsonParse, getFullpairByIndex, deadline, calcFee, getKeys, toHex, transformTx, getTransactions, getWeb3, getDec, calcGasPrice, createTransaction, checkDecodedData, pushTx, checkTxStatus, getBalance, out$ = typeof exports != 'undefined' && exports || this, toString$ = {}.toString;
  stringify = require('qs').stringify;
  ref$ = require('prelude-ls'), filter = ref$.filter, map = ref$.map, foldl = ref$.foldl, each = ref$.each;
  ref$ = require('../math.ls'), plus = ref$.plus, minus = ref$.minus, times = ref$.times, div = ref$.div;
  get = require('superagent').get;
  Web3 = require('web3');
  Tx = require('ethereumjs-tx');
  BN = require('ethereumjs-util').BN;
  jsonParse = require('../json-parse.ls');
  getFullpairByIndex = require('whitebox').getFullpairByIndex;
  deadline = require('../deadline.ls');
  out$.calcFee = calcFee = function(arg$, cb){
    var network, tx, feeType, account, amount, to, data, web3;
    network = arg$.network, tx = arg$.tx, feeType = arg$.feeType, account = arg$.account, amount = arg$.amount, to = arg$.to, data = arg$.data;
    if (feeType !== 'auto') {
      return cb(null);
    }
    web3 = getWeb3(network);
    return calcGasPrice({
      web3: web3,
      feeType: feeType
    }, function(err, gasPrice){
      if (err != null) {
        return cb(err);
      }
      return web3.eth.getTransactionCount(account.address, 'pending', function(err, nonce){
        var from;
        if (err != null) {
          return cb(err);
        }
        from = account.address;
        return web3.eth.estimateGas({
          from: from,
          nonce: nonce,
          to: to,
          data: data
        }, function(err, estimate){
          var dec, res, val;
          if (err != null) {
            return cb(err);
          }
          dec = getDec(network);
          res = times(gasPrice, estimate);
          val = div(res, Math.pow(10, 18));
          return cb(null, val);
        });
      });
    });
  };
  out$.getKeys = getKeys = function(arg$, cb){
    var network, mnemonic, index, result;
    network = arg$.network, mnemonic = arg$.mnemonic, index = arg$.index;
    result = getFullpairByIndex(mnemonic, index, network);
    return cb(null, result);
  };
  toHex = function(it){
    return new BN(it);
  };
  transformTx = curry$(function(network, t){
    var url, dec, tx, amount, time, fee;
    url = network.api.url;
    dec = getDec(network);
    network = 'eth';
    tx = t.hash;
    amount = div(t.value, dec);
    time = t.timeStamp;
    url = url + "/tx/" + tx;
    fee = div(times(t.cumulativeGasUsed, t.gasPrice), dec);
    return {
      network: network,
      tx: tx,
      amount: amount,
      fee: fee,
      time: time,
      url: url,
      from: t.from,
      to: t.to
    };
  });
  out$.getTransactions = getTransactions = function(arg$, cb){
    var network, address, apiUrl, module, action, startblock, endblock, sort, apikey, query;
    network = arg$.network, address = arg$.address;
    apiUrl = network.api.apiUrl;
    module = 'account';
    action = 'txlist';
    startblock = 0;
    endblock = 99999999;
    sort = 'asc';
    apikey = '4TNDAGS373T78YJDYBFH32ADXPVRMXZEIG';
    query = stringify({
      module: module,
      action: action,
      apikey: apikey,
      address: address,
      sort: sort,
      startblock: startblock,
      endblock: endblock
    });
    return get(apiUrl + "?" + query).timeout({
      deadline: deadline
    }).end(function(err, resp){
      if (err != null) {
        return cb(err);
      }
      return jsonParse(resp.text, function(err, result){
        var txs;
        if (err != null) {
          return cb(err);
        }
        if (toString$.call(result != null ? result.result : void 8).slice(8, -1) !== 'Array') {
          return cb("Unexpected result");
        }
        txs = map(transformTx(network))(
        result.result);
        return cb(null, txs);
      });
    });
  };
  getWeb3 = function(network){
    var web3Provider;
    web3Provider = network.api.web3Provider;
    return new Web3(new Web3.providers.HttpProvider(web3Provider));
  };
  getDec = function(network){
    var decimals;
    decimals = network.decimals;
    return Math.pow(10, decimals);
  };
  calcGasPrice = function(arg$, cb){
    var web3, feeType;
    web3 = arg$.web3, feeType = arg$.feeType;
    if (feeType === 'cheap') {
      return cb(null, '3000000000');
    }
    return web3.eth.getGasPrice(cb);
  };
  out$.createTransaction = createTransaction = curry$(function(arg$, cb){
    var network, account, recipient, amount, amountFee, data, feeType, txType, web3, dec, privateKey;
    network = arg$.network, account = arg$.account, recipient = arg$.recipient, amount = arg$.amount, amountFee = arg$.amountFee, data = arg$.data, feeType = arg$.feeType, txType = arg$.txType;
    web3 = getWeb3(network);
    dec = getDec(network);
    privateKey = new Buffer(account.privateKey.replace(/^0x/, ''), 'hex');
    return web3.eth.getTransactionCount(account.address, 'pending', function(err, nonce){
      var toWei, toEth, value;
      toWei = function(it){
        return times(it, dec);
      };
      toEth = function(it){
        return div(it, dec);
      };
      value = toWei(amount);
      return calcGasPrice({
        web3: web3,
        feeType: feeType
      }, function(err, gasPrice){
        var gasEstimate;
        if (err != null) {
          return cb(err);
        }
        gasEstimate = div(toWei(amountFee), gasPrice);
        return web3.eth.getBalance(account.address, function(err, balance){
          var balanceEth, tx, rawtx;
          if (err != null) {
            return cb(err);
          }
          balanceEth = toEth(balance);
          if (+balanceEth < +plus(amount, amountFee)) {
            return cb("Balance is not enough to send tx");
          }
          tx = new Tx({
            nonce: toHex(nonce),
            gasPrice: toHex(gasPrice),
            value: toHex(value),
            gas: toHex(gasEstimate),
            to: recipient,
            from: account.address,
            data: data != null ? data : ""
          });
          tx.sign(privateKey);
          rawtx = '0x' + tx.serialize().toString('hex');
          return cb(null, {
            rawtx: rawtx
          });
        });
      });
    });
  });
  out$.checkDecodedData = checkDecodedData = function(decodedData, data){
    if (!(decodedData != null ? decodedData : "").length === 0) {
      return false;
    }
    if (!(data != null ? data : "").length === 0) {
      return false;
    }
  };
  out$.pushTx = pushTx = curry$(function(arg$, cb){
    var network, rawtx, web3;
    network = arg$.network, rawtx = arg$.rawtx;
    web3 = getWeb3(network);
    return web3.eth.sendSignedTransaction(rawtx, function(err, txid){
      return cb(err, txid);
    });
  });
  out$.checkTxStatus = checkTxStatus = function(arg$, cb){
    var network, tx;
    network = arg$.network, tx = arg$.tx;
    return cb("Not Implemented");
  };
  out$.getBalance = getBalance = function(arg$, cb){
    var network, address, web3;
    network = arg$.network, address = arg$.address;
    web3 = getWeb3(network);
    return web3.eth.getBalance(address, function(err, number){
      var dec, balance;
      if (err != null) {
        return cb(err);
      }
      dec = getDec(network);
      balance = div(number, dec);
      return cb(null, balance);
    });
  };
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
