// Generated by LiveScript 1.5.0
(function(){
  var react;
  react = require('react');
  module.exports = function(name){
    return react.createElement('i', {
      className: "zmdi-" + name + " zmdi"
    });
  };
}).call(this);
