// Generated by LiveScript 1.6.0
(function(){
  var react;
  react = require('react');
  module.exports = function(){
    var children;
    return react.createElement('div', {
      className: 'loading-page loading-page-1737251852'
    }, children = react.createElement('div', {
      className: 'loading'
    }, children = [
      react.createElement('div', {
        className: 'inner one'
      }), react.createElement('div', {
        className: 'inner two'
      }), react.createElement('div', {
        className: 'inner three'
      })
    ]));
  };
}).call(this);
