// Generated by LiveScript 1.6.0
(function(){
  var react;
  react = require('react');
  module.exports = function(){
    var children;
    return react.createElement('div', {
      key: "loading",
      className: 'loading-page loading-page-399608342'
    }, children = react.createElement('div', {
      className: 'loading'
    }, children = [
      react.createElement('div', {
        key: "loading-1",
        className: 'inner one'
      }), react.createElement('div', {
        key: "loading-2",
        className: 'inner two'
      }), react.createElement('div', {
        key: "loading-3",
        className: 'inner three'
      })
    ]));
  };
}).call(this);
