// Generated by LiveScript 1.5.0
(function(){
  var origin, href, pathname;
  origin = "http://127.0.0.1";
  href = "https://127.0.0.1";
  pathname = '/';
  module.exports = typeof location != 'undefined' && location !== null
    ? location
    : {
      href: href,
      pathname: pathname,
      origin: origin
    };
}).call(this);
