// Generated by LiveScript 1.5.0
(function(){
  var observer, ref$, observable, toJS, render, react, app, dataScheme, window, navigate, web3, store, Main, web3t, bootstrap, out$ = typeof exports != 'undefined' && exports || this;
  observer = require('mobx-react').observer;
  ref$ = require('mobx'), observable = ref$.observable, toJS = ref$.toJS;
  render = require('react-dom').render;
  react = require('react');
  app = require('./app.ls');
  dataScheme = require('./data-scheme.ls');
  window = require('./browser/window.ls');
  navigate = require('./navigate.ls');
  web3 = require('./web3.ls');
  store = observable(dataScheme);
  Main = observer(function(arg$){
    var store;
    store = arg$.store;
    return app({
      store: store
    });
  });
  out$.web3t = web3t = web3(store);
  out$.bootstrap = bootstrap = function(root){
    store.root = root;
    return render(react.createElement(Main, {
      store: store
    }), root);
  };
  importAll$(window, out$);
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
