// Generated by LiveScript 1.5.0
(function(){
  var observer, ref$, observable, toJS, render, react, app, dataScheme, fake, refreshWallet, store, Main;
  observer = require('mobx-react').observer;
  ref$ = require('mobx'), observable = ref$.observable, toJS = ref$.toJS;
  render = require('react-dom').render;
  react = require('react');
  app = require('./app.ls');
  dataScheme = require('./data-scheme.ls');
  fake = require('./fake.ls');
  refreshWallet = require('./refresh-wallet.ls');
  store = observable(dataScheme);
  fake(store);
  refreshWallet(store, function(){});
  Main = observer(function(arg$){
    var store;
    store = arg$.store;
    return app({
      store: store
    });
  });
  window.onload = function(){
    return render(react.createElement(Main, {
      store: store
    }), document.body.appendChild(document.createElement('app')));
  };
}).call(this);
