// Generated by LiveScript 1.6.0
(function(){
  var window, pages, saved, oldseed, transaction, getPage, initControl, toString$ = {}.toString;
  window = require('./browser/window.ls');
  pages = require('./pages.ls');
  saved = require('./seed.ls').saved;
  oldseed = require('./oldseed.ls');
  transaction = require('mobx').transaction;
  getPage = function(store, page){
    var stage2;
    if (page !== ':init') {
      return page;
    }
    stage2 = store.current.page === 'locked' && !saved();
    if (stage2) {
      store.current.seed = oldseed();
    }
    if (stage2) {
      return 'newseed';
    }
    return 'wallets';
  };
  initControl = function(store, name, cb){
    var control;
    control = pages[name];
    if (toString$.call(control != null ? control.init : void 8).slice(8, -1) !== 'Function') {
      return cb(null);
    }
    return control.init(store, cb);
  };
  module.exports = function(store, page){
    window.scrollTo(0, 0);
    store.current.page = 'loading';
    return setTimeout(function(){
      var name;
      name = getPage(store, page);
      return initControl(store, name, function(){
        window.scrollTo(0, 0);
        return store.current.page = name;
      });
    }, 1);
  };
}).call(this);
