// Generated by LiveScript 1.5.0
(function(){
  var nem, get, jsonParse, ref$, filter, map, head, minus, div, getKeys, transformTransfer, getTransactions, createTransaction, pushTx, getBalance, out$ = typeof exports != 'undefined' && exports || this;
  nem = require('nem-sdk')['default'];
  get = require('superagent').get;
  jsonParse = require('../json-parse.ls');
  ref$ = require('prelude-ls'), filter = ref$.filter, map = ref$.map, head = ref$.head;
  ref$ = require('../math.ls'), minus = ref$.minus, div = ref$.div;
  out$.getKeys = getKeys = function(arg$, cb){
    var network, mnemonic, index, privateKey, kp, address;
    network = arg$.network, mnemonic = arg$.mnemonic, index = arg$.index;
    privateKey = nem.crypto.helpers.derivePassSha(mnemonic, 6000).priv;
    kp = nem.crypto.keyPair.create(nem.utils.helpers.fixPrivateKey(privateKey));
    address = nem.model.address.toAddress(kp.publicKey.toString(), network.id);
    return cb(null, {
      address: address,
      privateKey: privateKey
    });
  };
  transformTransfer = curry$(function(network, tx){
    var amount, fee, time, to, from, url;
    amount = tx.amount;
    fee = tx.fee;
    time = tx.timestamp_unix;
    to = tx.r_printablekey;
    from = tx.s_printablekey;
    url = network.api.url + "/" + tx.id;
    return {
      network: network,
      tx: tx,
      amount: amount,
      fee: fee,
      time: time,
      url: url,
      from: from,
      to: to
    };
  });
  out$.getTransactions = getTransactions = function(arg$, cb){
    var network, address;
    network = arg$.network, address = arg$.address;
    return get(network.api.apiUrl + "/account?address=" + address).end(function(err, data){
      if (err != null) {
        return cb(err);
      }
      return jsonParse(data.text, function(err, result){
        if (result.raw == null) {
          return cb(null, []);
        }
        if (err != null) {
          return cb(err);
        }
        return get(network.api.apiUrl + "/account_transactions?id=" + result.raw.id + "&iid=0").end(function(err, data){
          if (err != null) {
            return cb(err);
          }
          return jsonParse(data.text, function(err, result){
            var txs;
            if (err != null) {
              return cb(err);
            }
            txs = map(transformTransfer)(
            result.transfers);
            return cb(null, txs);
          });
        });
      });
    });
  };
  out$.createTransaction = createTransaction = curry$(function(arg$, cb){
    var network, sender, recepient, amount, amountFee, data, common, transferTransaction, transactionEntity, kp, serialized, signature, result, rawtx;
    network = arg$.network, sender = arg$.sender, recepient = arg$.recepient, amount = arg$.amount, amountFee = arg$.amountFee, data = arg$.data;
    if (network == null || sender == null || recepient == null || amountFee == null) {
      return cb("Params are required");
    }
    common = nem.model.objects.get('common');
    transferTransaction = nem.model.objects.get('transferTransaction');
    transferTransaction.amount = amount;
    transferTransaction.message = data != null ? data : "";
    transferTransaction.recipient = recepient;
    transactionEntity = nem.model.transactions.prepare('transferTransaction')(common, transferTransaction, network.id);
    kp = nem.crypto.keyPair.create(nem.utils.helpers.fixPrivateKey(sender.privateKey));
    serialized = nem.utils.serialization.serializeTransaction(transactionEntity);
    signature = kp.sign(serialized);
    result = {
      data: nem.utils.convert.ua2hex(serialized),
      signature: signature.toString()
    };
    rawtx = JSON.stringify(result);
    return cb(null, {
      rawtx: rawtx
    });
  });
  out$.pushTx = pushTx = curry$(function(arg$, cb){
    var network, rawtx, endpoint, success, failed;
    network = arg$.network, rawtx = arg$.rawtx;
    endpoint = nem.model.objects.create('endpoint')(network.api.nodeAddress, network.api.nodePort);
    success = function(res){
      if (res.code >= 2) {
        return cb(res.message);
      }
    };
    cb(null, res.message);
    failed = function(res){
      return cb(res);
    };
    return nem.com.requests.transaction.announce(endpoint, rawtx).then(success, failed);
  });
  out$.getBalance = getBalance = function(arg$, cb){
    var network, address;
    network = arg$.network, address = arg$.address;
    return get(network.api.apiUrl + "/account?address=" + address).end(function(err, data){
      if (err != null) {
        return cb(err);
      }
      return jsonParse(data.text, function(err, result){
        var input, output, saldo, print, this$ = this;
        if (err != null) {
          return cb(err);
        }
        if (result.raw == null) {
          return cb(null, "0");
        }
        input = head(
        map(function(it){
          return it.sum;
        })(
        filter(function(it){
          return it.type === 1;
        })(
        result.raw.balance)));
        output = head(
        map(function(it){
          return it.sum;
        })(
        filter(function(it){
          return it.type === 2;
        })(
        result.raw.balance)));
        if (input == null) {
          return cb(null, "0");
        }
        saldo = minus(input, output != null ? output : 0);
        print = div(saldo, Math.pow(10, 6));
        return cb(null, print);
      });
    });
  };
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
