// Generated by LiveScript 1.5.0
(function(){
  var whitebox, networks, ref$, objToPairs, pairsToObj, map, toJS, getFullpairByIndex, generateWallet, generateKeys, importMaster;
  whitebox = require('whitebox');
  networks = require('./networks.ls');
  ref$ = require('prelude-ls'), objToPairs = ref$.objToPairs, pairsToObj = ref$.pairsToObj, map = ref$.map;
  toJS = require('mobx').toJS;
  getFullpairByIndex = whitebox.getFullpairByIndex, generateWallet = whitebox.generateWallet, generateKeys = whitebox.generateKeys;
  importMaster = function(mnemonic){
    var keys;
    keys = generateKeys(mnemonic);
    return {
      mnemonic: mnemonic,
      address: keys.address,
      privateKey: keys.privateKey
    };
  };
  module.exports = function(mnemonic){
    var master, generateCoinWallet, wallets;
    mnemonic == null && (mnemonic = "");
    master = importMaster(mnemonic);
    generateCoinWallet = function(arg$){
      var name, network, index, balance, balanceUsd, usdRate, wallet;
      name = arg$[0], network = arg$[1];
      index = 1;
      balance = "...";
      balanceUsd = "...";
      usdRate = "...";
      wallet = getFullpairByIndex(master.mnemonic, index, network);
      return wallet.network = network, wallet.balance = balance, wallet.balanceUsd = balanceUsd, wallet.usdRate = usdRate, wallet.mnemonic = master.mnemonic, wallet;
    };
    wallets = map(generateCoinWallet)(
    objToPairs(
    networks));
    return {
      mnemonic: master.mnemonic,
      wallets: wallets,
      address: master.address,
      privateKey: master.privateKey
    };
  };
}).call(this);
