// Generated by LiveScript 1.5.0
(function(){
  var wallets, history, send, loading, notFound, out$ = typeof exports != 'undefined' && exports || this;
  wallets = require('./wallets.ls');
  history = require('./history.ls');
  send = require('./send.ls');
  out$.loading = loading = function(){
    return react.createElement('div', {
      className: 'loading'
    }, ' Loading...');
  };
  out$.notFound = notFound = function(){
    return react.createElement('div', {}, ' Page Not Found');
  };
  out$.wallets = wallets;
  out$.history = history;
  out$.send = send;
}).call(this);
