// Generated by LiveScript 1.6.0
(function(){
  var filter, plugins, coins, out$ = typeof exports != 'undefined' && exports || this;
  filter = require('prelude-ls').filter;
  plugins = [require('./plugins/btc-coin.ls'), require('./plugins/ltc-coin.ls'), require('./plugins/eth-coin.ls'), require('./plugins/dash-coin.ls'), require('./plugins/xem-coin.ls'), require('./plugins/sprkl-coin.ls')];
  out$.coins = coins = filter(function(it){
    return it.enabled;
  })(
  filter(function(it){
    return it.type === 'coin';
  })(
  plugins));
}).call(this);
