// Generated by LiveScript 1.6.0
(function(){
  var filter, getInstallList, common, getCoins, out$ = typeof exports != 'undefined' && exports || this;
  filter = require('prelude-ls').filter;
  getInstallList = require('./install-plugin.ls').getInstallList;
  common = [require('./plugins/btc-coin.ls'), require('./plugins/ltc-coin.ls'), require('./plugins/eth-coin.ls'), require('./plugins/dash-coin.ls')];
  out$.getCoins = getCoins = function(){
    var base, installed;
    base = filter(function(it){
      return it.enabled;
    })(
    filter(function(it){
      return it.type === 'coin';
    })(
    common));
    installed = filter(function(it){
      return it.type === 'coin';
    })(
    getInstallList());
    return base.concat(installed);
  };
}).call(this);
