// Generated by LiveScript 1.6.0
(function(){
  var react, QRCode, navigate;
  react = require('react');
  QRCode = require('qrcode.react');
  navigate = require('./navigate.ls');
  module.exports = function(arg$){
    var store, send, wallet, back, children;
    store = arg$.store;
    send = store.current.send;
    wallet = send.coin.wallet;
    back = function(){
      return navigate(store, 'send');
    };
    return react.createElement('div', {
      className: 'receive receive-1708377641'
    }, children = [
      react.createElement('div', {
        className: 'receive-body'
      }, children = react.createElement(QRCode, {
        value: wallet.address + "",
        size: "256"
      })), react.createElement('div', {
        className: 'bottom'
      }, children = react.createElement('a', {
        onClick: back
      }, ' Back'))
    ]);
  };
}).call(this);
