// Generated by LiveScript 1.5.0
(function(){
  var calcWallet, loadAllTransactions, loadRates, refreshWallet;
  calcWallet = require('./calc-wallet.ls');
  loadAllTransactions = require('./transactions.ls').loadAllTransactions;
  loadRates = require('./load-rates.ls');
  refreshWallet = function(store, cb){
    store.current.refreshing = true;
    calcWallet(store);
    return loadRates(store, function(){
      return loadAllTransactions(store, function(){
        calcWallet(store);
        store.current.refreshing = false;
        return cb(null);
      });
    });
  };
  module.exports = refreshWallet;
}).call(this);
