// Generated by LiveScript 1.5.0
(function(){
  var newAccount, refreshWallet;
  newAccount = require('./new-account.ls');
  refreshWallet = require('./refresh-wallet.ls');
  module.exports = function(web3, store, cb){
    return newAccount(store, store.current.seed, function(err, account){
      if (err != null) {
        return cb(err);
      }
      store.current.account = account;
      return refreshWallet(web3, store, cb);
    });
  };
}).call(this);
