// Generated by LiveScript 1.5.0
(function(){
  var localStorage, set, get, out$ = typeof exports != 'undefined' && exports || this;
  localStorage = require('localStorage');
  out$.set = set = function(seed){
    return localStorage.setItem('seed', seed);
  };
  out$.get = get = function(){
    var ref$;
    return (ref$ = localStorage.getItem('seed')) != null ? ref$ : "";
  };
}).call(this);
