// Generated by LiveScript 1.5.0
(function(){
  var state, activateForm, waitFormResult, notifyFormResult, out$ = typeof exports != 'undefined' && exports || this, toString$ = {}.toString;
  state = {};
  activateForm = function(store){};
  out$.waitFormResult = waitFormResult = function(id, cb){
    activateForm();
    return state[id] = cb;
  };
  out$.notifyFormResult = notifyFormResult = function(id, err, data){
    var ref$;
    if (toString$.call(state[id]).slice(8, -1) !== 'Function') {
      return;
    }
    state[id](err, data);
    return ref$ = state[id], delete state[id], ref$;
  };
}).call(this);
