// Generated by LiveScript 1.5.0
(function(){
  var react, navigate;
  react = require('react');
  navigate = require('./navigate.ls');
  module.exports = function(arg$){
    var store, goHome, children;
    store = arg$.store;
    goHome = function(){
      return navigate(store, 'wallets');
    };
    return react.createElement('div', {
      className: 'sent sent-1645795966'
    }, children = [
      react.createElement('div', {
        className: 'icon'
      }, children = react.createElement('img', {
        src: "./res/sent.png"
      })), react.createElement('div', {
        className: 'text'
      }, children = [
        react.createElement('span', {}, ' Your '), react.createElement('a', {
          href: store.current.lastTxUrl + "",
          target: "_blank"
        }, ' transaction'), react.createElement('span', {}, '  has been sent')
      ]), react.createElement('a', {
        onClick: goHome,
        className: 'button'
      }, ' Home')
    ]);
  };
}).call(this);
