// Generated by LiveScript 1.6.0
(function(){
  var cut, formatMoney, add, money, out$ = typeof exports != 'undefined' && exports || this;
  out$.cut = cut = function(str, number){
    var n, s;
    if (str == null) {
      return "";
    }
    n = number != null ? number : 10;
    s = str.toString();
    if (s.length > n) {
      return s.substr(0, n) + '...';
    } else {
      return s;
    }
  };
  formatMoney = function(value){};
  add = function(all, next){
    var l, comma;
    l = [3, 7, 11, 15, 19, 23];
    comma = l.indexOf(all.length) > -1 ? ',' : "";
    return next + comma + all;
  };
  out$.money = money = function(value){
    var ref$, head, tail, h, t, e;
    if (value == null) {
      return null;
    }
    ref$ = value.toString().split('.'), head = ref$[0], tail = ref$[1];
    h = head.split("").reverse().reduce(add, "");
    t = (tail != null ? tail : "000").substr(0, 3);
    e = (function(){
      switch (t.length) {
      case 3:
        return t;
      case 2:
        return t + "0";
      case 1:
        return t + "00";
      case 0:
        return "00";
      }
    }());
    return h + "." + e;
  };
}).call(this);
