// Generated by LiveScript 1.6.0
(function(){
  var mainnet, testnet, type, enabled, token, color, image, usdInfo, out$ = typeof exports != 'undefined' && exports || this;
  out$.mainnet = mainnet = {
    decimals: 8,
    txFee: '0.0001',
    txFeeOptions: {
      fast: '0.0002',
      cheap: '0.00005546',
      auto: '0.0002'
    },
    txFeeIn: 'btc',
    mask: '1000000000000000000000000000000000',
    api: {
      apiUrl: 'https://api.omniwallet.org',
      apiUrlBtc: 'https://insight.bitpay.com',
      provider: 'omni',
      url: 'https://omniexplorer.info',
      decimal: 8
    },
    propertyid: '31',
    messagePrefix: '\x18Bitcoin Signed Message:\n',
    bech32: 'bc',
    bip32: {
      'public': 0x0488b21e,
      'private': 0x0488ade4
    },
    pubKeyHash: 0x00,
    scriptHash: 0x05,
    wif: 0x80
  };
  out$.testnet = testnet = {
    txFee: '0.0001',
    txFeeOptions: {
      fast: '0.0001',
      cheap: '0.00005546',
      auto: '0.0002'
    },
    txFeeIn: 'btc',
    disabled: true,
    decimals: 8,
    mask: '1000000000000000000000000000000000',
    api: {
      provider: 'insight',
      url: 'https://testnet.blockexplorer.com',
      apiUrl: 'https://api.omniwallet.org',
      apiUrlBtc: 'https://testnet.blockexplorer.com',
      decimal: 8
    },
    messagePrefix: '\x18Bitcoin Signed Message:\n',
    propertyid: '31',
    bech32: 'tb',
    bip32: {
      'public': 0x043587cf,
      'private': 0x04358394
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef
  };
  out$.type = type = 'coin';
  out$.enabled = enabled = true;
  out$.token = token = 'usdt';
  out$.color = color = '#26A17B';
  out$.image = image = 'https://res.cloudinary.com/nixar-work/image/upload/v1547940263/download.png';
  out$.usdInfo = usdInfo = "url(https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETH,LTC,DASH,XEM,USDT&tsyms=USD).USDT.USD";
}).call(this);
