// Generated by LiveScript 1.6.0
(function(){
  var react, ref$, cut, money, each, web3, CopyToClipboard, copiedInform, copy, round5;
  react = require('react');
  ref$ = require('./tools.ls'), cut = ref$.cut, money = ref$.money;
  each = require('prelude-ls').each;
  web3 = require('./web3.ls');
  CopyToClipboard = require('react-copy-to-clipboard').CopyToClipboard;
  copiedInform = require('./copied-inform.ls');
  copy = require('./copy.ls');
  round5 = require('./round5.ls');
  module.exports = curry$(function(store, wallets, wallet){
    var index, type, lweb3, addressLabel, send, usdRate, ref$, expand, active, balance, children;
    index = wallets.indexOf(wallet);
    type = (function(){
      switch (false) {
      case index !== 0:
        return 'top';
      case index + 1 !== wallets.length:
        return 'bottom';
      default:
        return 'middle';
      }
    }());
    if (store == null || wallet == null) {
      return null;
    }
    lweb3 = web3(store);
    addressLabel = (function(){
      switch (false) {
      case wallet.coin.token !== 'xem':
        return 'account';
      default:
        return 'address';
      }
    }());
    send = curry$(function(wallet, event){
      var sendTransaction, to, value;
      if (wallet == null) {
        return alert("Not yet loaded");
      }
      sendTransaction = lweb3[wallet.coin.token].sendTransaction;
      to = "";
      value = 0;
      return sendTransaction({
        to: to,
        value: value
      }, function(err){
        if (err != null) {
          return console.log(err);
        }
      });
    });
    usdRate = (ref$ = wallet != null ? wallet.usdRate : void 8) != null ? ref$ : 0;
    expand = function(){
      return store.current.walletIndex = index;
    };
    active = index === store.current.walletIndex ? 'active' : '';
    balance = round5(wallet.balance) + ' ' + wallet.coin.token.toUpperCase();
    return react.createElement('div', {
      onClick: expand,
      key: wallet.coin.token + "",
      className: active + " wallet wallet1729544693"
    }, children = [
      react.createElement('div', {
        className: 'wallet-top'
      }, children = [
        react.createElement('div', {
          className: 'top-left'
        }, children = [
          react.createElement('div', {
            className: 'img'
          }, children = react.createElement('img', {
            src: wallet.coin.image + ""
          })), react.createElement('div', {
            className: 'info'
          }, children = [
            react.createElement('div', {
              className: 'name'
            }, ' PRICE'), react.createElement('div', {
              className: 'price'
            }, ' $' + money(usdRate))
          ])
        ]), react.createElement('div', {
          className: 'top-middle'
        }, children = [
          react.createElement('div', {
            className: 'balance'
          }, ' Balance'), react.createElement('div', {
            className: 'balance'
          }, ' ' + balance)
        ]), react.createElement('div', {
          className: 'top-right'
        }, children = react.createElement('button', {
          onClick: send(wallet)
        }, ' Open'))
      ]), react.createElement('div', {
        className: 'wallet-middle'
      }, children = [
        react.createElement('a', {
          target: "_blank",
          href: wallet.network.api.url + "/" + addressLabel + "/" + wallet.address
        }, ' ' + wallet.address), react.createElement(CopyToClipboard, {
          text: wallet.address + "",
          onCopy: copiedInform(store)
        }, children = copy(store))
      ])
    ]);
  });
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
