// Generated by LiveScript 1.6.0
(function(){
  var react, wallet, ref$, map, take, drop, menu, get, web3, navigate, arrow, wallets;
  react = require('react');
  wallet = require('./wallet.ls');
  ref$ = require('prelude-ls'), map = ref$.map, take = ref$.take, drop = ref$.drop;
  menu = require('./menu.ls');
  get = require('./seed.ls').get;
  web3 = require('./web3.ls');
  navigate = require('./navigate.ls');
  arrow = 'https://res.cloudinary.com/dfbhd7liw/image/upload/v1543595868/wallet/arrow.png';
  wallets = function(arg$){
    var store, list, max, canUp, canDown, goUp, goDown, wallets, children;
    store = arg$.store;
    if (store.current.account == null) {
      return null;
    }
    list = store.current.list;
    max = 4;
    canUp = store.current.list > 0;
    canDown = store.current.list + 4 < store.current.account.wallets.length / max;
    goUp = function(){
      if (!canUp) {
        return;
      }
      store.current.list -= max;
      return store.current.walletIndex = 0;
    };
    goDown = function(){
      if (!canDown) {
        return;
      }
      store.current.list += max;
      return store.current.walletIndex = 0;
    };
    wallets = take(max)(
    drop(list)(
    store.current.account.wallets));
    return react.createElement('div', {
      key: "wallets"
    }, children = [
      menu({
        store: store
      }), react.createElement('div', {
        key: "wallets-body",
        className: 'wallets wallets-1312736338'
      }, children = [
        react.createElement('div', {
          onClick: goUp,
          key: "arrow-up",
          className: canUp + " arrow arrow-t"
        }, children = react.createElement('img', {
          src: arrow + ""
        })), react.createElement('div', {
          key: "wallets-viewport",
          className: 'wallet-container'
        }, children = map(wallet(store, wallets))(
        wallets)), react.createElement('div', {
          onClick: goDown,
          key: "arrow-down",
          className: canDown + " arrow arrow-d"
        }, children = react.createElement('img', {
          src: arrow + ""
        }))
      ])
    ]);
  };
  wallets.init = function(store, cb){
    if (store.current.account != null) {
      return cb(null);
    }
    store.current.seed = get();
    return web3(store).refresh(function(err){
      return cb(err);
    });
  };
  module.exports = wallets;
}).call(this);
