// Generated by LiveScript 1.6.0
(function(){
  var react, wallet, ref$, map, take, drop, menu, get, web3, navigate, arrow, wallets;
  react = require('react');
  wallet = require('./wallet.ls');
  ref$ = require('prelude-ls'), map = ref$.map, take = ref$.take, drop = ref$.drop;
  menu = require('./menu.ls');
  get = require('./seed.ls').get;
  web3 = require('./web3.ls');
  navigate = require('./navigate.ls');
  arrow = 'https://res.cloudinary.com/dfbhd7liw/image/upload/v1543595868/wallet/arrow.png';
  wallets = function(arg$){
    var store, children;
    store = arg$.store;
    if (store.current.account == null) {
      return null;
    }
    return react.createElement('div', {}, children = [
      menu({
        store: store
      }), react.createElement('div', {
        className: 'wallets wallets621879901'
      }, children = react.createElement('div', {
        className: 'wallets-container'
      }, children = [
        react.createElement('div', {
          className: 'arrow arrow-t'
        }, children = react.createElement('img', {
          src: arrow + ""
        })), react.createElement('div', {
          className: 'wallets wallets621879901'
        }, children = map(wallet(store))(
        take(4)(
        drop(0)(
        store.current.account.wallets)))), react.createElement('div', {
          className: 'arrow arrow-d'
        }, children = react.createElement('img', {
          src: arrow + ""
        }))
      ]))
    ]);
  };
  wallets.init = function(store, cb){
    if (store.current.account != null) {
      return cb(null);
    }
    store.current.seed = get();
    return web3(store).refresh(function(err){
      return cb(err);
    });
  };
  module.exports = wallets;
}).call(this);
