// Generated by LiveScript 1.5.0
(function(){
  var react, wallet, map, menu;
  react = require('react');
  wallet = require('./wallet.ls');
  map = require('prelude-ls').map;
  menu = require('./menu.ls');
  module.exports = function(arg$){
    var store, children;
    store = arg$.store;
    return react.createElement('div', {}, children = [
      menu({
        store: store
      }), react.createElement('div', {
        className: 'wallets wallets-153557454'
      }, children = map(wallet(store))(
      store.current.account.wallets))
    ]);
  };
}).call(this);
