// Generated by LiveScript 1.5.0
(function(){
  var react, ref$, cut, money, each, web3;
  react = require('react');
  ref$ = require('./tools.ls'), cut = ref$.cut, money = ref$.money;
  each = require('prelude-ls').each;
  web3 = require('./web3.ls');
  module.exports = curry$(function(store, wallet){
    var lweb3, send, history, children;
    if (store == null || wallet == null) {
      return null;
    }
    lweb3 = web3(store);
    send = curry$(function(wallet, event){
      var sendTransaction, to, value;
      sendTransaction = lweb3[wallet.network.token].sendTransaction;
      to = "";
      value = 0;
      return sendTransaction({
        to: to,
        value: value
      }, function(err){
        return console.log(err);
      });
    });
    history = curry$(function(wallet, event){
      store.current.filter = ['IN', 'OUT', wallet.network.token];
      return store.current.page = 'history';
    });
    return react.createElement('div', {
      key: wallet.network.token + "",
      className: 'wallet wallet-1442129510'
    }, children = [
      react.createElement('div', {
        className: 'wallet-header'
      }, children = [
        react.createElement('div', {
          className: 'part left'
        }, children = [
          react.createElement('div', {
            className: 'cell'
          }, children = react.createElement('img', {
            src: wallet.network.image + ""
          })), react.createElement('div', {
            className: 'cell'
          }, children = [
            react.createElement('div', {}, ' ' + wallet.network.token.toUpperCase()), react.createElement('div', {
              className: 'gray'
            }, ' $' + money(wallet.usdRate))
          ])
        ]), react.createElement('div', {
          className: 'part center'
        }, children = [
          react.createElement('div', {}, ' ' + cut(wallet.balance) + ' '), react.createElement('div', {
            className: 'gray'
          }, ' $' + money(wallet.balanceUsd))
        ]), react.createElement('div', {
          className: 'part right'
        }, children = [
          react.createElement('div', {}, children = react.createElement('a', {
            onClick: send(wallet),
            className: 'btn default'
          }, ' Send')), react.createElement('div', {}, children = react.createElement('a', {
            onClick: history(wallet),
            className: 'btn'
          }, ' history'))
        ])
      ]), react.createElement('div', {
        className: 'wallet-body'
      }, children = react.createElement('div', {
        className: 'group center'
      }, children = react.createElement('span', {
        className: 'address'
      }, children = react.createElement('a', {
        target: "_blank",
        href: wallet.network.api.url + "/address/" + wallet.address
      }, ' ' + wallet.address))))
    ]);
  });
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
