// Generated by LiveScript 1.5.0
(function(){
  var get, div, createTransaction, pushTx, getBalance, getTransactions, out$ = typeof exports != 'undefined' && exports || this;
  get = require('superagent').get;
  div = require('../math.ls').div;
  out$.createTransaction = createTransaction = curry$(function(arg$, cb){
    var sender, recepient, amount, amountFee;
    sender = arg$.sender, recepient = arg$.recepient, amount = arg$.amount, amountFee = arg$.amountFee;
    return cb("Not implemented");
  });
  out$.pushTx = pushTx = curry$(function(arg$, cb){
    var network, rawtx;
    network = arg$.network, rawtx = arg$.rawtx;
    return cb("Not implemented");
  });
  out$.getBalance = getBalance = function(arg$, cb){
    var address;
    address = arg$.address;
    return get("https://nodes.wavesnodes.com/addresses/balance/" + address).timeout({
      deadline: 15000
    }).end(function(err, res){
      var result, balance;
      if (err != null) {
        return cb(err);
      }
      result = JSON.parse(res.text);
      balance = div(result.balance, 100000000);
      cb(null, balance);
    });
  };
  out$.getTransactions = getTransactions = function(arg$, cb){
    var network, address;
    network = arg$.network, address = arg$.address;
    return cb(null, []);
  };
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
