// Generated by LiveScript 1.6.0
(function(){
  var getCoins, ref$, objToPairs, map, pairsToObj, each, guid, waitFormResult, changeAmount, div, plus, web3, protect, navigate, useNetwork, getBalance, buildInstall, refreshAccount, state, titles, showCases, buildGetBalance, buildSendTransaction, buildNetworkSpecific, buildApi, buildUse, getApis, clearApi, refreshApis, slice$ = [].slice, toString$ = {}.toString;
  getCoins = require('./plugin-loader.ls').getCoins;
  ref$ = require('prelude-ls'), objToPairs = ref$.objToPairs, map = ref$.map, pairsToObj = ref$.pairsToObj, each = ref$.each;
  guid = require('./guid.ls');
  waitFormResult = require('./send-form.ls').waitFormResult;
  changeAmount = require('./change-amount.ls');
  ref$ = require('./math.ls'), div = ref$.div, plus = ref$.plus;
  web3 = require('../eth.ls');
  protect = require('protect');
  navigate = require('./navigate.ls');
  useNetwork = require('./use-network.ls');
  getBalance = require('./api.ls').getBalance;
  buildInstall = require('./install-plugin.ls').buildInstall;
  refreshAccount = require('./refresh-account.ls');
  state = {
    time: null
  };
  titles = ['name@email.com', 'name.ethnamed.io', 'domain.com'];
  showCases = function(store, arg$, cb){
    var title, titles;
    title = arg$[0], titles = slice$.call(arg$, 1);
    if (title == null) {
      return cb(null);
    }
    store.current.sendToMask = title;
    return setTimeout(function(){
      return showCases(store, titles, function(){
        return cb(null);
      });
    }, 1000);
  };
  buildGetBalance = function(store, coin){
    return function(cb){
      var network, wallet;
      network = coin[store.current.network];
      wallet = coin.wallet;
      return getBalance({
        token: coin.token,
        network: network,
        address: wallet.address
      }, cb);
    };
  };
  buildSendTransaction = function(store, coin){
    return function(tx, cb){
      var network, to, data, decodedData, value, gas, ref$, id, current, send, amountObtain, amountObtainUsd, amountSendUsd, amountSendFee, amountSendFeeUsd, proposeEscrow, amountSend, helps;
      network = coin[store.current.network];
      if (toString$.call(tx).slice(8, -1) !== 'Object') {
        return cb("Transaction is required");
      }
      to = tx.to, data = tx.data, decodedData = tx.decodedData, value = tx.value, gas = tx.gas;
      if (toString$.call(tx.to).slice(8, -1) !== 'String') {
        return cb("Recepient (to) is required");
      }
      if ((ref$ = toString$.call(value).slice(8, -1)) !== 'String' && ref$ !== 'Number') {
        return cb("Value is required");
      }
      id = guid();
      current = store.current;
      send = current.send;
      amountObtain = '0';
      amountObtainUsd = '0';
      amountSendUsd = '0';
      amountSendFee = '0';
      amountSendFeeUsd = '0';
      proposeEscrow = false;
      amountSend = div(value, Math.pow(10, network.decimals));
      importAll$(send, {
        to: to,
        data: data,
        decodedData: decodedData,
        network: network,
        coin: coin,
        value: value,
        gas: gas,
        id: id,
        amountSend: amountSend,
        amountObtain: amountObtain,
        amountObtainUsd: amountObtainUsd,
        amountSendUsd: amountSendUsd,
        amountSendFee: amountSendFee,
        amountSendFeeUsd: amountSendFeeUsd,
        proposeEscrow: proposeEscrow
      });
      changeAmount(store, amountSend);
      navigate(store, 'send');
      helps = titles.concat([network.mask]);
      showCases(store, helps, function(){});
      return waitFormResult(id, function(err, data){
        if (err != null) {
          return cb(err);
        }
        return cb(null, data);
      });
    };
  };
  buildNetworkSpecific = function(coin){
    switch (false) {
    case coin.token !== 'eth':
      return web3.eth;
    default:
      return {};
    }
  };
  buildApi = function(store, it){
    var sendTransaction, getBalance;
    sendTransaction = buildSendTransaction(store, it);
    getBalance = buildGetBalance(store, it);
    return importAll$(buildNetworkSpecific(it), {
      sendTransaction: sendTransaction,
      getBalance: getBalance
    });
  };
  buildUse = function(web3, store){
    return function(network){
      return useNetwork(web3, store, network, function(){});
    };
  };
  getApis = function(cweb3, store){
    return pairsToObj(
    map(function(it){
      return [it.token, buildApi(store, it)];
    })(
    getCoins()));
  };
  clearApi = curry$(function(cweb3, name){
    var ref$;
    return ref$ = cweb3[name], delete cweb3[name], ref$;
  });
  refreshApis = function(cweb3, store){
    var ref$, apis;
    each(clearApi(cweb3))(
    (ref$ = refreshApis.prev) != null
      ? ref$
      : []);
    apis = getApis(cweb3, store);
    importAll$(cweb3, apis);
    return refreshApis.prev = Object.keys(apis);
  };
  module.exports = function(store){
    var cweb3, use, install, refresh;
    cweb3 = {};
    use = buildUse(cweb3, store);
    install = buildInstall(cweb3, store);
    refresh = function(cb){
      refreshApis(cweb3, store);
      return refreshAccount(cweb3, store, function(err){
        if (err != null) {
          return cb(err);
        }
        return cb(null);
      });
    };
    refreshApis(cweb3, store);
    importAll$(cweb3, {
      utils: web3.utils,
      use: use,
      refresh: refresh,
      install: install
    });
    return cweb3;
  };
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
