// Generated by LiveScript 1.5.0
(function(){
  var location, document, scrollTo, mockWindow;
  location = require('./location.ls');
  document = {};
  scrollTo = function(){};
  mockWindow = {
    scrollTo: scrollTo,
    location: location,
    document: document
  };
  module.exports = typeof window != 'undefined' && window !== null ? window : mockWindow;
}).call(this);
