// Generated by LiveScript 1.5.0
(function(){
  var mainnet, testnet, type, enabled, token, image, out$ = typeof exports != 'undefined' && exports || this;
  out$.mainnet = mainnet = {
    messagePrefix: 'Monero',
    api: {
      provider: 'cryptonote'
    }
  };
  out$.testnet = testnet = {
    messagePrefix: 'Monero',
    api: {
      provider: 'cryptonote'
    }
  };
  out$.type = type = 'coin';
  out$.enabled = enabled = false;
  out$.token = token = 'xmr';
  out$.image = image = 'https://prostocoin.com/assets/coins/xmr.png';
}).call(this);
